Feat/product page
oparenko/fake-burrberry-frontend pull request #1
Opened 2017-08-02 00:24 UTC by oparenko

🤔

2017-08-02 11:02 UTC, evgenyrodionov commented
Непонятно проверять или нет — ты коммитил, ревью не перевесил, мб ты ещё 10 коммитов накинешь пока я буду проверять

2017-08-02 11:56 UTC, oparenko commented
Упс, сорян, забыл про это. Еще раз.

2017-08-02 18:02 UTC, evgenyrodionov commented
https://rawgit.com/oparenko/fake-burrberry-frontend/feat/product-page/index.html

пикчи посыпались

2017-08-02 18:04 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28887462-f6652148-77c5-11e7-9a36-7058cc4c2d0c.png)
![image](https://user-images.githubusercontent.com/775692/28887479-ff2fcea4-77c5-11e7-9f1c-99ad3036cdce.png)
![image](https://user-images.githubusercontent.com/775692/28887490-0787020c-77c6-11e7-8cfe-e5557da4bcb6.png)
![image](https://user-images.githubusercontent.com/775692/28887501-0f3f9068-77c6-11e7-9a2a-5eb854660a03.png)
![image](https://user-images.githubusercontent.com/775692/28887511-162e73e4-77c6-11e7-8b80-2ca3ddcfbab0.png)

2017-08-02 23:45 UTC, oparenko commented
Теперь все пофиксил.

Единствое различие с макетом 1px, потому что в макете ошибка: высота кнопки Description должна быть 85px, а 84px (исходя из того, что Shipping & Returns — 86px-1px из-за отсутсвия border-bottom).

2017-08-03 11:08 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28919237-484d8880-7855-11e7-8370-bcb1f7c2fc3f.png)

2017-08-03 11:10 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28919261-638410e2-7855-11e7-8adc-2087f5b43649.png)
![image](https://user-images.githubusercontent.com/775692/28919269-6c57fed6-7855-11e7-953a-8098fe353be0.png)

2017-08-03 11:11 UTC, imevro requested changes
слишком задротский нейминг, попробуй бэм

2017-08-03 11:11 UTC, evgenyrodionov commented on css/style.css
> +* {
нельзя так делать!!!!!!!!!!!!!!!!!!!!!!!!

2017-08-03 11:11 UTC, evgenyrodionov commented on css/style.css
> +  outline: none;
ТЕМ БОЛЕЕ http://www.outlinenone.com/

2017-08-03 11:11 UTC, evgenyrodionov commented on index.html
> +        <ul class="product-characteristics">
с сервера не приходят классы

2017-08-03 11:11 UTC, evgenyrodionov commented on index.html
> +        <div class="recommended-product-card">
поч не ссылкой

2017-08-03 19:10 UTC, oparenko commented
Все пофиксил теперь.

2017-08-03 19:17 UTC, oparenko commented
Все пофиксил теперь.

2017-08-04 19:42 UTC, evgenyrodionov commented
На след проверку

2017-08-04 21:05 UTC, imevro requested changes

2017-08-04 21:05 UTC, evgenyrodionov commented on index.html
> +        <a class="more__link" href="#">Men’s Black Trench Coats</a>
куда отступы уехали

2017-08-05 14:02 UTC, imevro approved these changes
делай планшет

2017-08-06 09:16 UTC, merged