Product page react
oparenko/fake-burrberry-frontend pull request #3
Opened 2017-08-10 17:31 UTC by oparenko

Сделал все, что было в домашке до десктопа.

+ Все зависимости в package.json
+ Тайтлы через react-helmet
+ Нормальные manifest.json и package.json
+ README.md должен быть про проект
+ Нейминг должен быть корректным
+ Архитектура должна быть про продукт
+ Избавляйтесь от избыточных префиксов
+ Функции — тупым компонентам, классы — рабочим
+ ЦСС-импорты должны быть один раз 
+ Шрифты только через Гугл Фонтс
+ Поставьте prettier
+ Интерфейсные изображения импортами, остальное в `/public`
+ Главный файл в директории index.js или index.jsx

2017-08-10 22:38 UTC, imevro requested changes

2017-08-10 22:38 UTC, evgenyrodionov commented on src/App.jsx
> +import Main from "./Product/Show/index.jsx";
Main from 'Product/Show' как-то несогласованно

2017-08-10 22:38 UTC, evgenyrodionov commented on src/App.jsx
> +import Main from "./Product/Show/index.jsx";
index.jsx можно опустить, в телеграфе объяснял

2017-08-10 22:38 UTC, evgenyrodionov commented on src/App.jsx
> +class App extends Component {
зачем тут класс

2017-08-10 22:38 UTC, evgenyrodionov commented on src/App.jsx
> +import Footer from "./Footer.jsx";
.jsx тоже можно опустить — вебпак сам ищет js/jsx-файлы

2017-08-10 22:38 UTC, evgenyrodionov commented on src/Footer.jsx
> +              <NavigationLink href="#">Payment</NavigationLink>
а обязательно навигейшенлинк? разве тут будут другие линки?

2017-08-10 22:38 UTC, evgenyrodionov commented on src/Product/Show/Divider.jsx
> +export default () => (
можно сразу экспортить стайлед-компонент, смысл создавать ещё один для его экспорта

2017-08-10 22:38 UTC, evgenyrodionov commented on src/Product/Show/Metadata.jsx
> +  <div className="col-xs-12 col-md-5">
вытащи сетку за пределы компонента — что будет если я захочу переиспользовать в другом компоненте с другой раскладкой?

2017-08-10 22:38 UTC, evgenyrodionov commented on src/Product/Show/Shipping.jsx
> +  h5 {
это не с сервера приходит

2017-08-10 22:38 UTC, evgenyrodionov commented on src/Product/Show/Slider.jsx
> +        srcset="img/Long-Cotton-Gabardine-Car-Coat-1@2x.jpg 2x, img/Long-Cotton-Gabardine-Car-Coat-1@3x.jpg 3x"
srcset → srcSet

2017-08-10 22:38 UTC, evgenyrodionov commented on src/index.js
> +WebFont.load({
зачем? это создаёт оверхед, link stylesheet прекрасно справляется с шрифтами

2017-08-11 16:44 UTC, oparenko commented
Все пофиксил из вчерашнего.

2017-08-11 17:55 UTC, imevro requested changes

2017-08-11 17:55 UTC, evgenyrodionov commented on src/Product/Show/Recommended.jsx
> +            <ProductName>Relaxed Fit Stretch Jeans Content For Three Lines</ProductName>
а будет другой нейм? зачем префикс продакт?

2017-08-11 17:55 UTC, evgenyrodionov commented on src/Product/Show/Slider.jsx
> +  <div className="col-xs-12 col-md-7">
что будет если я захочу заиспользовать этот компонент в других колонках? никогда не вкладывай колонки в компоненты

2017-08-11 20:58 UTC, oparenko commented
Поправил, начинаю работать над десктопом.

2017-08-11 23:18 UTC, imevro approved these changes
вроде норм

2017-08-12 06:44 UTC, oparenko commented
Добавил десктоп.

2017-08-12 12:38 UTC, imevro requested changes

2017-08-12 12:38 UTC, evgenyrodionov commented on src/Product/Show/Breakpoints.jsx
> +export const Desktop = ({ children }) => <Responsive minWidth={'62rem'} children={children} />;
нет такого десктоп/таблет, есть размер экрана

2017-08-12 12:38 UTC, evgenyrodionov commented on src/Product/Show/Info.jsx
> +    <FreeDelivery>
а если станет не фри?

2017-08-12 13:17 UTC, oparenko commented
Поправил нейминг брейкпоинтов и переименовал Delivery компонент.

2017-08-12 17:52 UTC, imevro requested changes

2017-08-12 17:52 UTC, evgenyrodionov commented on src/Product/Show/Breakpoints.jsx
> +export const MinDeviceWidthLarge = ({ children }) => <Responsive minWidth={'62rem'} children={children} />;
бля как сложно, назови просто Large

2017-08-12 17:52 UTC, evgenyrodionov commented on src/Product/Show/Breakpoints.jsx
>  import React from 'react';
а почему этот файл лежит в продакт/шоу? какое он имеет отношение к товарам? что будет, если в личном кабинете он нам понадобится?

2017-08-12 17:52 UTC, evgenyrodionov commented on src/Product/Show/Breakpoints.jsx
> +export const MinDeviceWidthLarge = ({ children }) => <Responsive minWidth={'62rem'} children={children} />;
чилдрен нужно передавать не пропом, а контентом между тегами

2017-08-12 17:52 UTC, evgenyrodionov commented on src/Product/Show/index.jsx
> +            <MaxDeviceWidthLarge>
мы не живем max-ами, я говорил об этом несколько раз

2017-08-12 22:19 UTC, oparenko commented
Вынес Breakpoints.jsx в Common, переименовал их и перенес чилдрен в контент между теги.

2017-08-13 10:33 UTC, merged