Feat/products page
oparenko/fake-burrberry-frontend pull request #5
Opened 2017-08-19 01:35 UTC by oparenko

https://build-fobpgyizhk.now.sh

Макет неидеально совпадает с версткой потому что в макете есть баги (ikorsar их все перечислил в своем ПРе). По цифрам же — все как в макете.

2017-08-19 09:40 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485474-34a44296-84db-11e7-946b-4f0ff87482b3.png)
![image](https://user-images.githubusercontent.com/775692/29485478-46988584-84db-11e7-81e5-515b4e0868fd.png)
![image](https://user-images.githubusercontent.com/775692/29485479-4e6d5956-84db-11e7-89dc-36e77527ca47.png)
![image](https://user-images.githubusercontent.com/775692/29485485-6727f71c-84db-11e7-8a71-59fdc0b14615.png)
![image](https://user-images.githubusercontent.com/775692/29485489-756b2e20-84db-11e7-968e-18e44631b304.png)
![image](https://user-images.githubusercontent.com/775692/29485493-7e71cb8c-84db-11e7-9bd9-b0a304985bd2.png)
![image](https://user-images.githubusercontent.com/775692/29485495-84ed6bc4-84db-11e7-8f06-4af531a2f5e8.png)

2017-08-19 11:46 UTC, oparenko commented
Пофиксил — https://build-deojrgecrn.now.sh.

Есть небольшое различие с макетом в двух местах:

- кнопка "Show 9 more" 50 пикселей вместо 48 в макете
- кнопка лайк выровняна вертикально по верху всего блока Description, а не центрирована по лейблу (потому что лейбла может и не быть)

2017-08-19 13:00 UTC, oparenko commented
Про process.env.PUBLIC_URL увидел твой коммент 10 минут назад, не успел еще поправить, но поправлю.

2017-08-19 14:04 UTC, imevro requested changes

2017-08-19 14:04 UTC, evgenyrodionov commented on package.json
> +    "eslint": "4.00",
не понял

2017-08-19 14:04 UTC, evgenyrodionov commented on src/App.jsx
> +        <Helmet defaultTitle="Burrberry" titleTemplate="%s Burrberry" />
Burberry не Burrberry

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Common/Breakpoints.jsx
> +  (<Responsive minWidth={'768'} maxWidth={992}>
поч 768 строкой

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Header/MenuFull.jsx
> +      <LinkStyled active to="/products/men">
Используй https://reacttraining.com/react-router/web/api/NavLink

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +const Heritage = [
это реакт-компонент?

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +    link: '/products/men/heritage-trench-coats/the-westminster–long-heritage-trench-coat',
линк ручками делай

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +          {SingleBreasted.map(item =>
item → product

2017-08-19 14:04 UTC, evgenyrodionov commented on src/Product/Show/index.jsx
> +      <title>Long Cotton Gabardine Car Coat | Men |</title>
а зачем руками постоянно в конце ставить | если можно в темплейт засунуть?

2017-08-19 14:09 UTC, oparenko commented on package.json
> +    "eslint": "4.00",
`npm WARN eslint-loader@1.7.1 requires a peer of eslint@>=1.6.0 <4.0.0 but none was installed.`

был вот такой вот ворнинг

2017-08-19 16:27 UTC, oparenko commented
Все поправил — https://build-kcsdvkhgxf.now.sh

2017-08-19 18:42 UTC, imevro requested changes

2017-08-19 18:42 UTC, evgenyrodionov commented on src/Header/MenuFull.jsx
> +  activeClassName,
а зачем это делать?

2017-08-19 18:42 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +        <LinkStyled to={`/products/men/trench-coats/${props.uid}`}>
почему бы сверху не передавать в Card один проп `to`? зачем его трижды конструировать тут?

2017-08-19 22:11 UTC, oparenko commented
Готово — https://build-ubrwuyadvh.now.sh

2017-08-20 09:10 UTC, imevro approved these changes

2017-08-20 09:11 UTC, merged