Feat/interactive like button
oparenko/fake-burrberry-frontend pull request #8
Opened 2017-08-28 20:23 UTC by oparenko

Пока что только кнопка лайк.

2017-08-28 21:21 UTC, evgenyrodionov commented on package.json
> +    "flexboxgrid2": "^7.0.0-alpha7",
I appreciate that

2017-08-28 21:22 UTC, imevro requested changes

2017-08-28 21:22 UTC, evgenyrodionov commented on src/Product/Card/LikeButton/Heart.jsx
> +      fill={props.isLiked ? '#171717' : 'none'}
у тебя компонент-иконка, а ты а) хранишь его в product card что-то там б) передаешь пропы, которые его никак не касаются — почему бы не передавать просто fill={}?

эту иконку можно где угодно будет переиспользовать, а ты завязываешься

2017-08-28 22:41 UTC, oparenko commented
Вынес Heart.jsx в отдельную папку Icons.

2017-08-29 09:38 UTC, imevro requested changes

2017-08-29 09:38 UTC, imevro commented on src/Icons/Heart.jsx
> +      fill={props.fillColor}
почему бы не просто fill?

2017-08-29 09:49 UTC, oparenko commented
Поправил.

2017-08-29 18:56 UTC, merged