Feat/colour size buttons
oparenko/fake-burrberry-frontend pull request #9
Opened 2017-08-31 21:39 UTC by oparenko

Сделал кнопки выбора цвета и размера — http://oparenko-burberry-fake-shop-for-study-dev.now.sh/

2017-09-01 11:05 UTC, evgenyrodionov commented
Почему задеплоено на дев?

2017-09-01 11:07 UTC, evgenyrodionov commented
Что с кнопкой файнд ин стор

![image](https://user-images.githubusercontent.com/775692/29967337-e0daf9ae-8f1e-11e7-9dab-1531fcb03263.png)

2017-09-01 11:09 UTC, imevro submitted a review, later dismissed

2017-09-01 11:09 UTC, evgenyrodionov commented on src/Product/Show/Colors.jsx
> +    selectedColor: 'Honey',
читай телеграф

2017-09-01 11:09 UTC, evgenyrodionov commented on src/Product/Show/index.jsx
> +                src="https://assets.burberry.com/is/image/Burberryltd/98b658a12f42e12facf56ca59c87a33084b76231.jpg?$BBY_V2_ML_3X4$&hei=960&wid=720"
а удалить из проекта?

2017-09-01 15:49 UTC, oparenko commented
Все пофиксил — https://build-pxhhsoxqho.now.sh.

2017-09-01 17:18 UTC, imevro requested changes

2017-09-01 17:18 UTC, evgenyrodionov commented on src/Product/Show/Sizes.jsx
> +    this.setState({ selectSizeIndex: +e.target.id });
что за плюс?

2017-09-02 01:14 UTC, oparenko commented on src/Product/Show/Sizes.jsx
> +    this.setState({ selectSizeIndex: +e.target.id });
Поправил — сделал одинаково в размерах и цветах.

https://build-aizducducs.now.sh

Делаю фильтры и селекты.

2017-09-02 08:23 UTC, closed without merging